stages:
  - hello-jobs

debian_job:
  stage: hello-jobs
  image: debian:12
  tags:
    - local
  script:
    - apt update
    - apt install -y cowsay
    - export PATH="$PATH:/usr/games"
    - cowsay "Hello from debian_job!"

ubuntu_job:
  stage: hello-jobs
  image: ubuntu:24.04
  tags:
    - local
  script:
    - echo "Hello from ubuntu_job!"

manual_job:
  stage: .post
  image: ubuntu:22.04
  tags:
    - local
  when: manual
  script:
    - echo "Hello from manual_job!"
